import { ThemeConfig, ThemeKey } from '../types';

export const THEMES: Record<ThemeKey, ThemeConfig> = {
  'professional-polish': {
    id: 'professional-polish',
    name: 'โปรเฟสชั่นแนล โพลิช (Professional Polish)',
    nameEn: 'Professional Polish',
    description: 'โทนขาวครีมไอวอรี่ระดับพรีเมียม สไตล์ Modern Executive Barber & Salon สะอาดตา คมชัดทุกมิติ',
    badge: '✨ สว่าง สะอาด พรีเมียม (แนะนำ)',
    isDark: false,
    bgMain: 'bg-[#fdfdfb] text-slate-900',
    bgCard: 'bg-white border border-slate-200/90 shadow-sm shadow-slate-200/50',
    bgCardHover: 'hover:border-slate-300 hover:shadow-md transition-all',
    borderSubtle: 'border-slate-200',
    borderActive: 'border-slate-900',
    primary: 'bg-slate-900 text-white hover:bg-slate-800 font-semibold shadow-sm',
    primaryHover: 'hover:bg-slate-800',
    primaryLight: 'bg-amber-50 text-amber-900 border border-amber-200',
    primaryText: 'text-amber-700',
    accent: 'from-slate-900 to-slate-800',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-slate-200/80 shadow-xs',
    tabActiveBg: 'bg-slate-900 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0f172a',
    inputBg: 'bg-slate-50 border-slate-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-slate-50/80 border border-slate-100',
  },
  'luxury-gold': {
    id: 'luxury-gold',
    name: 'ทองคำหรูหรา (Luxury Gold)',
    nameEn: 'Luxury Gold',
    description: 'โทนสีดำคลาสสิกแซมด้วยทองคำพรีเมียม สไตล์ Master Barber ระดับบน',
    badge: '👑 เรียบหรูยอดนิยม',
    isDark: true,
    bgMain: 'bg-zinc-950 text-zinc-100',
    bgCard: 'bg-zinc-900/90 border border-amber-500/20 shadow-xl shadow-black/40',
    bgCardHover: 'hover:border-amber-500/40',
    borderSubtle: 'border-zinc-800',
    borderActive: 'border-amber-500',
    primary: 'bg-gradient-to-r from-amber-500 to-amber-600 text-zinc-950 font-semibold shadow-md shadow-amber-500/20',
    primaryHover: 'hover:from-amber-400 hover:to-amber-500',
    primaryLight: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',
    primaryText: 'text-amber-400',
    accent: 'from-amber-400 to-yellow-500',
    headerBg: 'bg-zinc-950/90 backdrop-blur-md border-b border-amber-500/15',
    tabActiveBg: 'bg-amber-500 text-zinc-950 font-semibold shadow-md shadow-amber-500/25',
    tabActiveText: 'text-zinc-950 font-semibold',
    colorSwatch: '#f59e0b',
    inputBg: 'bg-zinc-950 border-zinc-700 text-zinc-100 placeholder:text-zinc-500 focus:border-amber-500',
    textHeading: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    cardInnerBg: 'bg-zinc-950/60 border border-zinc-800',
  },
  'charcoal-classic': {
    id: 'charcoal-classic',
    name: 'ชาร์โคลมินิมอล (Modern Slate)',
    nameEn: 'Modern Slate',
    description: 'โทนสีเทาดำชาร์โคลสะอาดตา มินิมอลสว่าง เน้นความคมชัด อ่านง่าย',
    badge: '✨ มินิมอลสะอาดตา',
    isDark: true,
    bgMain: 'bg-slate-900 text-slate-100',
    bgCard: 'bg-slate-800/90 border border-slate-700/60 shadow-xl shadow-black/30',
    bgCardHover: 'hover:border-slate-500/60',
    borderSubtle: 'border-slate-700',
    borderActive: 'border-sky-400',
    primary: 'bg-gradient-to-r from-sky-500 to-blue-600 text-white font-semibold shadow-md shadow-sky-500/20',
    primaryHover: 'hover:from-sky-400 hover:to-blue-500',
    primaryLight: 'bg-sky-500/10 text-sky-400 border border-sky-500/20',
    primaryText: 'text-sky-400',
    accent: 'from-sky-400 to-blue-500',
    headerBg: 'bg-slate-900/90 backdrop-blur-md border-b border-slate-800',
    tabActiveBg: 'bg-sky-500 text-white font-semibold shadow-md shadow-sky-500/25',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0ea5e9',
    inputBg: 'bg-slate-950 border-slate-700 text-slate-100 placeholder:text-slate-500 focus:border-sky-400',
    textHeading: 'text-slate-100',
    textMuted: 'text-slate-400',
    cardInnerBg: 'bg-slate-950/60 border border-slate-800',
  },
  'modern-sage': {
    id: 'modern-sage',
    name: 'เขียวเซจผ่อนคลาย (Modern Sage)',
    nameEn: 'Modern Sage',
    description: 'โทนเขียวมัทฉะและเอิร์ธโทน สไตล์ Barber & Salon โมเดิร์นธรรมชาติ',
    badge: '🌿 สดชื่นผ่อนคลาย',
    isDark: true,
    bgMain: 'bg-stone-950 text-stone-100',
    bgCard: 'bg-stone-900/90 border border-emerald-500/20 shadow-xl shadow-black/40',
    bgCardHover: 'hover:border-emerald-500/40',
    borderSubtle: 'border-stone-800',
    borderActive: 'border-emerald-500',
    primary: 'bg-gradient-to-r from-emerald-500 to-teal-600 text-stone-950 font-semibold shadow-md shadow-emerald-500/20',
    primaryHover: 'hover:from-emerald-400 hover:to-teal-500',
    primaryLight: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
    primaryText: 'text-emerald-400',
    accent: 'from-emerald-400 to-teal-500',
    headerBg: 'bg-stone-950/90 backdrop-blur-md border-b border-emerald-500/15',
    tabActiveBg: 'bg-emerald-500 text-stone-950 font-semibold shadow-md shadow-emerald-500/25',
    tabActiveText: 'text-stone-950 font-semibold',
    colorSwatch: '#10b981',
    inputBg: 'bg-stone-950 border-stone-700 text-stone-100 placeholder:text-stone-500 focus:border-emerald-500',
    textHeading: 'text-stone-100',
    textMuted: 'text-stone-400',
    cardInnerBg: 'bg-stone-950/60 border border-stone-800',
  },
  'midnight-indigo': {
    id: 'midnight-indigo',
    name: 'มิดไนท์อินดิโก้ (Midnight Indigo)',
    nameEn: 'Midnight Indigo',
    description: 'โทนน้ำเงินเข้มลึก ลุคโมเดิร์นเทคโนโลยี ดูเฉียบคมและทรงพลัง',
    badge: '🌙 เท่เฉียบคม',
    isDark: true,
    bgMain: 'bg-gray-950 text-gray-100',
    bgCard: 'bg-gray-900/90 border border-indigo-500/20 shadow-xl shadow-black/40',
    bgCardHover: 'hover:border-indigo-500/40',
    borderSubtle: 'border-gray-800',
    borderActive: 'border-indigo-500',
    primary: 'bg-gradient-to-r from-indigo-500 to-violet-600 text-white font-semibold shadow-md shadow-indigo-500/20',
    primaryHover: 'hover:from-indigo-400 hover:to-violet-500',
    primaryLight: 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20',
    primaryText: 'text-indigo-400',
    accent: 'from-indigo-400 to-violet-500',
    headerBg: 'bg-gray-950/90 backdrop-blur-md border-b border-indigo-500/15',
    tabActiveBg: 'bg-indigo-500 text-white font-semibold shadow-md shadow-indigo-500/25',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#6366f1',
    inputBg: 'bg-gray-950 border-gray-700 text-gray-100 placeholder:text-gray-500 focus:border-indigo-500',
    textHeading: 'text-gray-100',
    textMuted: 'text-gray-400',
    cardInnerBg: 'bg-gray-950/60 border border-gray-800',
  },
  'warm-amber': {
    id: 'warm-amber',
    name: 'วินเทจวู้ดแลนด์ (Warm Amber & Wood)',
    nameEn: 'Warm Amber',
    description: 'โทนสีน้ำตาลไหม้และส้มอบอุ่น สไตล์ Vintage Barber ดั้งเดิม',
    badge: '🪵 วินเทจคลาสสิก',
    isDark: true,
    bgMain: 'bg-neutral-950 text-neutral-100',
    bgCard: 'bg-neutral-900/90 border border-orange-500/20 shadow-xl shadow-black/40',
    bgCardHover: 'hover:border-orange-500/40',
    borderSubtle: 'border-neutral-800',
    borderActive: 'border-orange-500',
    primary: 'bg-gradient-to-r from-orange-500 to-amber-600 text-neutral-950 font-semibold shadow-md shadow-orange-500/20',
    primaryHover: 'hover:from-orange-400 hover:to-amber-500',
    primaryLight: 'bg-orange-500/10 text-orange-400 border border-orange-500/20',
    primaryText: 'text-orange-400',
    accent: 'from-orange-400 to-amber-500',
    headerBg: 'bg-neutral-950/90 backdrop-blur-md border-b border-orange-500/15',
    tabActiveBg: 'bg-orange-500 text-neutral-950 font-semibold shadow-md shadow-orange-500/25',
    tabActiveText: 'text-neutral-950 font-semibold',
    colorSwatch: '#f97316',
    inputBg: 'bg-neutral-950 border-neutral-700 text-neutral-100 placeholder:text-neutral-500 focus:border-orange-500',
    textHeading: 'text-neutral-100',
    textMuted: 'text-neutral-400',
    cardInnerBg: 'bg-neutral-950/60 border border-neutral-800',
  },
  'ruby-luxury': {
    id: 'ruby-luxury',
    name: 'ทับทิมหรูหรา (Ruby Rose)',
    nameEn: 'Ruby Rose',
    description: 'โทนไวน์แดงทับทิม โดดเด่น สง่างาม สำหรับร้านซาลอน & บาร์เบอร์แนวหน้า',
    badge: '🍷 สง่างามโดดเด่น',
    isDark: true,
    bgMain: 'bg-zinc-950 text-zinc-100',
    bgCard: 'bg-zinc-900/90 border border-rose-500/20 shadow-xl shadow-black/40',
    bgCardHover: 'hover:border-rose-500/40',
    borderSubtle: 'border-zinc-800',
    borderActive: 'border-rose-500',
    primary: 'bg-gradient-to-r from-rose-500 to-pink-600 text-white font-semibold shadow-md shadow-rose-500/20',
    primaryHover: 'hover:from-rose-400 hover:to-pink-500',
    primaryLight: 'bg-rose-500/10 text-rose-400 border border-rose-500/20',
    primaryText: 'text-rose-400',
    accent: 'from-rose-400 to-pink-500',
    headerBg: 'bg-zinc-950/90 backdrop-blur-md border-b border-rose-500/15',
    tabActiveBg: 'bg-rose-500 text-white font-semibold shadow-md shadow-rose-500/25',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#f43f5e',
    inputBg: 'bg-zinc-950 border-zinc-700 text-zinc-100 placeholder:text-zinc-500 focus:border-rose-500',
    textHeading: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    cardInnerBg: 'bg-zinc-950/60 border border-zinc-800',
  },
};
